# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69cf315bc117931f4ce73da764b7a1e875975e32251bd01a1e9bd7bf72c0302a2b57afcce476d2ad2a5be016ef4ca3b2baf041f356fac1265dd16c0813f3cf1

test:
  secret_key_base: 8312fa23e3f8df1a6653c98ab03506aead1538af2e4d01c7104410306becebdde88d8634ba7e4280673bd717b2e57fb68b48a8c7ab565cef43ccf488aa867810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
